sudo: false
language: ruby
addons:
  postgresql: '9.4'
  apt:
    packages:
    - build-essential
    - ruby-dev
    - libproj-dev
    - libgeos-dev
    - libffi-dev
    - libsparsehash-dev
    - zlib1g-dev
    - libxslt1-dev
    - libxml2-dev
    - libbz2-dev
rvm:
  - 2.2.5
  - 2.3.1
notifications:
  email:
    - mflorisson@cityway.fr
    - bruno@atnos.com
    - metienne@cityway.fr
    - alban.peignier@af83.com
    - anicet.rohee@af83.com
  slack:
    secure: htRE80xSy1PEwrzny5UQlQRE4McSzyVJ05E6nyCPCiZwExydyUgHBBEuI/62weL90uWxlFaC7MrbqlhlVUZd4p7l8FwhOdFvWVYpkUgXRYNldA/V+LdLe4P7npJmgGZarnFEeu0ktV7A4ozLyUrKUvbfPSjp+JyzIiBNLoBOwv4=
before_install:
  - gem update bundler
before_script:
  - bundle exec rake ci:db_travis_config
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script: bundle exec rake spec
