deactivate_formats: # For example: 'hub,sig,neptune'
secret_key_base: # Generate with `bundle exec rake secret`
devise_secret_key: # Generate with `bundle exec rake secret`
api_endpoint:
google_analytic_tracker:
geoportail_api_key:
newrelic_licence_key:
osrm_endpoint:
capistrano_deploy_user:
app_version:
smtp_delivery_method: # letter_opener|smtp
smtp_host:
smtp_port:
smtp_domain:
smtp_user_name:
smtp_password:
smtp_authentication:

